services:
  database:
    env_file:
      - .env
    container_name: rn-database-cluster
    image: postgres:14-alpine
    ports:
      - 9005:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./entrypoints/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  storage:
    image: minio/minio
    container_name: rn-local-s3
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    command: server /data
    volumes:
      - minio_data:/data

  storage_mc:
    image: minio/mc
    container_name: rn-local-s3-mc
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://rn-local-s3:9000 minioadmin minioadminpassword)
      do sleep 2; done;
      echo '{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"s3:*\",\"Resource\":[\"arn:aws:s3:::*\",\"arn:aws:s3:::*/*\"]}]}' > /tmp/admin_policy.json;
      /usr/bin/mc admin policy create myminio admin /tmp/admin_policy.json;
      /usr/bin/mc mb myminio/mybucket;
      /usr/bin/mc admin user add myminio newadmin newadminpassword;
      /usr/bin/mc admin policy attach myminio admin --user=newadmin;
      "

volumes:
  minio_data:
  postgres_data:
