services:
  database:
    env_file:
      - .env
    container_name: rn-database-cluster
    image: postgres:14-alpine
    ports:
      - 9005:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./entrypoints/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  storage:
    env_file:
      - .env
    image: minio/minio
    container_name: rn-local-s3
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  storage_mc:
    env_file:
      - .env
    image: minio/mc
    container_name: rn-local-s3-mc
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set rn-local-s3 http://rn-local-s3:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD})
      do sleep 2; done;
      /usr/bin/mc mb rn-local-s3/${MINIO_BUCKET_NAME};
      "

volumes:
  minio_data:
  postgres_data:
