version: '3.9'

services:
  postgres:
    env_file:
      - .env
    container_name: rn-database-cluster
    image: postgres:14-alpine
    ports:
      - 9005:5432
    volumes:
      - ./tmp/docker/postgres:/var/lib/postgresql/data
      - ./entrypoints/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
