services:
  database:
    env_file:
      - .env
    container_name: rn-database-cluster
    image: postgres:14-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./entrypoints/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${DATABASE_USERNAME}
      - POSTGRES_USER=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

  caching:
    image: memcached:latest
    container_name: memcached
    environment:
      - MEMCACHED_MAX_MEMORY=64m # Maximum memory usage for items (default: 64m)
      - MEMCACHED_MAX_CONNECTIONS=1024 # Maximum number of simultaneous connections (default: 1024)
      - MEMCACHED_THREADS=4 # Number of threads to use (default: 4)
      - MEMCACHED_SLAB_PAGE_SIZE=1m # Size of memory pages in slabs (default: 1m)
      - MEMCACHED_VERBOSE=true # Enable verbose mode (default: false)
    ports:
      - '11211:11211'
    restart: unless-stopped

  storage:
    env_file:
      - .env
    image: minio/minio
    container_name: rn-local-s3
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  storage_mc:
    env_file:
      - .env
    image: minio/mc
    container_name: rn-local-s3-mc
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set rn-local-s3 http://rn-local-s3:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD})
      do sleep 2; done;
      /usr/bin/mc mb rn-local-s3/${MINIO_BUCKET_NAME};
      "

volumes:
  minio_data:
  postgres_data:
